title: "superpaintman.io"

seo:
    robots:
        index: true
        follow: true

    title: superpaintman.io
    description: SuperPaintman's jumppad
    keywords:
        - SuperPaintman
    local: en_US
    type: website
    url: https://superpaintman.io/
    site_name: superpaintman.io

    twitter:
        card: summary
        site: '@superpaintman'

links:
    habrahabr:
        name: "superpaintman"
        url:  "https://habrahabr.ru/users/superpaintman/"
    github:
        name: "SuperPaintman"
        url:  "https://github.com/SuperPaintman/"
    # twitter:
    #     name: ""
    #     url:  ""
    npm:
        name: "SuperPaintman"
        url:  "https://www.npmjs.com/~superpaintman"
    dockerhub:
        name: "superpaintman"
        url:  "https://hub.docker.com/u/superpaintman/"
    # headhunter:
    #     name: ""
    #     url:  ""

counters:
    google: ""

footer:
    repo:
        name: GitHub
        url: https://github.com/SuperPaintman/superpaintman.io

    license:
        text: "Apache License, Version 2.0"
        url: https://raw.githubusercontent.com/SuperPaintman/superpaintman.io/master/LICENSE